=== BenjaminStahr/monk_simulator_programming_game/out/production/BenjaminStahrsMonkSimulator/xml/territory.dtd
<!ELEMENT territory (row+, territorySizeX, territorySizeY, monkPositionX, monkPositionY, monkDirection)>

<!ELEMENT territorySizeX (#PCDATA)>
<!ELEMENT territorySizeY (#PCDATA)>

<!ELEMENT row (tile+)>
<!ELEMENT tile (xPos, yPos, content)>
<!ELEMENT xPos (#PCDATA)>
<!ELEMENT yPos (#PCDATA)>
<!ELEMENT content (#PCDATA)>

<!ELEMENT monkPositionX (#PCDATA)>
<!ELEMENT monkPositionY (#PCDATA)>
<!ELEMENT monkDirection (#PCDATA)>

=== BenjaminStahr/monk_simulator_programming_game/src/xml/xmlTerritorys/exexexe.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE territory SYSTEM "C:\xampp\htdocs\JavaProjekt\src\territorys\xml\territory.dtd">
<territory>
<row>
<tile>
<xPos>0</xPos>
<yPos>0</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>0</xPos>
<yPos>1</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>0</xPos>
<yPos>2</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>0</xPos>
<yPos>3</yPos>
<content>badKarma</content>
</tile>
<tile>
<xPos>0</xPos>
<yPos>4</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>0</xPos>
<yPos>5</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>0</xPos>
<yPos>6</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>0</xPos>
<yPos>7</yPos>
<content>hole</content>
</tile>
</row>
<row>
<tile>
<xPos>1</xPos>
<yPos>0</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>1</xPos>
<yPos>1</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>1</xPos>
<yPos>2</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>1</xPos>
<yPos>3</yPos>
<content>badKarma</content>
</tile>
<tile>
<xPos>1</xPos>
<yPos>4</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>1</xPos>
<yPos>5</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>1</xPos>
<yPos>6</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>1</xPos>
<yPos>7</yPos>
<content>hole</content>
</tile>
</row>
<row>
<tile>
<xPos>2</xPos>
<yPos>0</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>2</xPos>
<yPos>1</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>2</xPos>
<yPos>2</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>2</xPos>
<yPos>3</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>2</xPos>
<yPos>4</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>2</xPos>
<yPos>5</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>2</xPos>
<yPos>6</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>2</xPos>
<yPos>7</yPos>
<content>hole</content>
</tile>
</row>
<row>
<tile>
<xPos>3</xPos>
<yPos>0</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>3</xPos>
<yPos>1</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>3</xPos>
<yPos>2</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>3</xPos>
<yPos>3</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>3</xPos>
<yPos>4</yPos>
<content>goodKarma</content>
</tile>
<tile>
<xPos>3</xPos>
<yPos>5</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>3</xPos>
<yPos>6</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>3</xPos>
<yPos>7</yPos>
<content>ground</content>
</tile>
</row>
<row>
<tile>
<xPos>4</xPos>
<yPos>0</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>4</xPos>
<yPos>1</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>4</xPos>
<yPos>2</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>4</xPos>
<yPos>3</yPos>
<content>goodKarma</content>
</tile>
<tile>
<xPos>4</xPos>
<yPos>4</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>4</xPos>
<yPos>5</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>4</xPos>
<yPos>6</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>4</xPos>
<yPos>7</yPos>
<content>hole</content>
</tile>
</row>
<row>
<tile>
<xPos>5</xPos>
<yPos>0</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>5</xPos>
<yPos>1</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>5</xPos>
<yPos>2</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>5</xPos>
<yPos>3</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>5</xPos>
<yPos>4</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>5</xPos>
<yPos>5</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>5</xPos>
<yPos>6</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>5</xPos>
<yPos>7</yPos>
<content>hole</content>
</tile>
</row>
<row>
<tile>
<xPos>6</xPos>
<yPos>0</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>6</xPos>
<yPos>1</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>6</xPos>
<yPos>2</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>6</xPos>
<yPos>3</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>6</xPos>
<yPos>4</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>6</xPos>
<yPos>5</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>6</xPos>
<yPos>6</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>6</xPos>
<yPos>7</yPos>
<content>hole</content>
</tile>
</row>
<row>
<tile>
<xPos>7</xPos>
<yPos>0</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>7</xPos>
<yPos>1</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>7</xPos>
<yPos>2</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>7</xPos>
<yPos>3</yPos>
<content>ground</content>
</tile>
<tile>
<xPos>7</xPos>
<yPos>4</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>7</xPos>
<yPos>5</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>7</xPos>
<yPos>6</yPos>
<content>hole</content>
</tile>
<tile>
<xPos>7</xPos>
<yPos>7</yPos>
<content>hole</content>
</tile>
</row>

<territorySizeX>8</territorySizeX>
<territorySizeY>8</territorySizeY>
<monkPositionX>3</monkPositionX>
<monkPositionY>5</monkPositionY>
<monkDirection>south</monkDirection>
</territory>
